  - name: Synchronize source code
    synchronize:
      src: "{{ local_app_path }}"
      dest: "{{ remote_app_path }}"
    
  - name: Install Python Django dependencies
    pip:
      requirements: "{{ app_path }}requirements.yml"

  - name: Changing perm of "manage.py", adding "+x"
    file: dest="{{ app_path }}notejam/manage.py" mode=a+x

#   - name: Sync database
#     django_manage: 
#       app_path: "{{ app_path }}"
#       command: syncdb

#   - name: Create superuser
#     django_manage:
#       command: "createsuperuser --noinput --username=Gago --email=hrach.hambaryan@gmail.com"
#       app_path: "{{ app_path }}"

  - name: Copy systemd service file to server
    copy:
      src: "{{ local_app_path }}/notejam.service"
      dest: /etc/systemd/system
      owner: root
      group: root

  - name: Start notejam service
    service:
      name: notejam.service
      enabled: yes

