  - name: Synchronize source code
    synchronize:
      src: "{{ local_app_path }}"
      dest: "{{ remote_app_path }}"
      
  - name: Copy systemd service file to server
    copy:
      src: "{{ local_app_path }}/notejam.service"
      dest: /etc/systemd/system
      owner: root
      group: root   
   
  - name: Install Python Django dependencies
    pip:
      requirements: "{{ remote_app_path }}requirements.txt"

  - name: Changing perm of "manage.py", adding "+x"
    file: dest="{{ remote_app_path }}notejam/manage.py" mode=a+x

  - name: modify settings.py to connect to db
    replace:
      path: '{{ remote_app_path }}notejam/notejam/settings.py'
      regexp: '{{  item.editable  }}'
      replace: '{{  item.edited  }}'
    loop:
      - { editable: '{{ engine }}', edited: '{{ engine_edited }}' }
      - { editable: '{{ name }}', edited: '{{ name_edited }}' }
      - { editable: '{{ user }}', edited: '{{ user_edited }}' }
      - { editable: '{{ pwd }}', edited: '{{ pwd_edited }}' }
      - { editable: '{{ host }}', edited: '{{ host_edited }}' }
      - { editable: '{{ port }}', edited: '{{ port_edited }}' }

#   - name: Sync database
#     django_manage: 
#       app_path: "{{ app_path }}"
#       command: syncdb

#   - name: Create superuser
#     django_manage:
#       command: "createsuperuser --noinput --username=Gago --email=hrach.hambaryan@gmail.com"
#       app_path: "{{ app_path }}"

  - name: Start notejam service
    service:
      name: notejam.service
      enabled: yes

