  - name: Copy source code
    copy:
      src: "../Django"
      dest: "/opt/"
      force: yes
    
  - name: Install Python Django dependencies
    pip:
      requirements: /opt/Django/requirements.txt

  - name: Changing perm of "manage.py", adding "+x"
    file: dest={{ app_path }}manage.py mode=a+x

#   - name: Sync database
#     django_manage: 
#       app_path: "{{ app_path }}"
#       command: syncdb

#   - name: Create superuser
#     django_manage:
#       command: "createsuperuser --noinput --username=Gago --email=hrach.hambaryan@gmail.com"
#       app_path: "{{ app_path }}"

  - name: Copy systemd service file to server
    copy:
      src: ./templates/notejam.service
      dest: /etc/systemd/system
      owner: root
      group: root
    notify:
      - Notejam service copied

  - name: Start notejam service
    service:
      name: notejam.service
#       state: started
      enabled: yes
    notify:
      - Notejam service started & enabled

